# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.31
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

import _lisa
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


class intArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, intArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, intArray, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _lisa.new_intArray(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _lisa.delete_intArray
    __del__ = lambda self : None;
    def __getitem__(*args): return _lisa.intArray___getitem__(*args)
    def __setitem__(*args): return _lisa.intArray___setitem__(*args)
    def cast(*args): return _lisa.intArray_cast(*args)
    __swig_getmethods__["frompointer"] = lambda x: _lisa.intArray_frompointer
    if _newclass:frompointer = staticmethod(_lisa.intArray_frompointer)
intArray_swigregister = _lisa.intArray_swigregister
intArray_swigregister(intArray)
intArray_frompointer = _lisa.intArray_frompointer

class doubleArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, doubleArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, doubleArray, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _lisa.new_doubleArray(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _lisa.delete_doubleArray
    __del__ = lambda self : None;
    def __getitem__(*args): return _lisa.doubleArray___getitem__(*args)
    def __setitem__(*args): return _lisa.doubleArray___setitem__(*args)
    def cast(*args): return _lisa.doubleArray_cast(*args)
    __swig_getmethods__["frompointer"] = lambda x: _lisa.doubleArray_frompointer
    if _newclass:frompointer = staticmethod(_lisa.doubleArray_frompointer)
doubleArray_swigregister = _lisa.doubleArray_swigregister
doubleArray_swigregister(doubleArray)
doubleArray_frompointer = _lisa.doubleArray_frompointer

class PySwigIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, PySwigIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PySwigIterator, name)
    def __init__(self): raise AttributeError, "No constructor defined"
    __repr__ = _swig_repr
    __swig_destroy__ = _lisa.delete_PySwigIterator
    __del__ = lambda self : None;
    def value(*args): return _lisa.PySwigIterator_value(*args)
    def incr(*args): return _lisa.PySwigIterator_incr(*args)
    def decr(*args): return _lisa.PySwigIterator_decr(*args)
    def distance(*args): return _lisa.PySwigIterator_distance(*args)
    def equal(*args): return _lisa.PySwigIterator_equal(*args)
    def copy(*args): return _lisa.PySwigIterator_copy(*args)
    def next(*args): return _lisa.PySwigIterator_next(*args)
    def previous(*args): return _lisa.PySwigIterator_previous(*args)
    def advance(*args): return _lisa.PySwigIterator_advance(*args)
    def __eq__(*args): return _lisa.PySwigIterator___eq__(*args)
    def __ne__(*args): return _lisa.PySwigIterator___ne__(*args)
    def __iadd__(*args): return _lisa.PySwigIterator___iadd__(*args)
    def __isub__(*args): return _lisa.PySwigIterator___isub__(*args)
    def __add__(*args): return _lisa.PySwigIterator___add__(*args)
    def __sub__(*args): return _lisa.PySwigIterator___sub__(*args)
    def __iter__(self): return self
PySwigIterator_swigregister = _lisa.PySwigIterator_swigregister
PySwigIterator_swigregister(PySwigIterator)

class VecDouble(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VecDouble, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VecDouble, name)
    __repr__ = _swig_repr
    def iterator(*args): return _lisa.VecDouble_iterator(*args)
    def __iter__(self): return self.iterator()
    def __nonzero__(*args): return _lisa.VecDouble___nonzero__(*args)
    def __len__(*args): return _lisa.VecDouble___len__(*args)
    def pop(*args): return _lisa.VecDouble_pop(*args)
    def __getslice__(*args): return _lisa.VecDouble___getslice__(*args)
    def __setslice__(*args): return _lisa.VecDouble___setslice__(*args)
    def __delslice__(*args): return _lisa.VecDouble___delslice__(*args)
    def __delitem__(*args): return _lisa.VecDouble___delitem__(*args)
    def __getitem__(*args): return _lisa.VecDouble___getitem__(*args)
    def __setitem__(*args): return _lisa.VecDouble___setitem__(*args)
    def append(*args): return _lisa.VecDouble_append(*args)
    def empty(*args): return _lisa.VecDouble_empty(*args)
    def size(*args): return _lisa.VecDouble_size(*args)
    def clear(*args): return _lisa.VecDouble_clear(*args)
    def swap(*args): return _lisa.VecDouble_swap(*args)
    def get_allocator(*args): return _lisa.VecDouble_get_allocator(*args)
    def begin(*args): return _lisa.VecDouble_begin(*args)
    def end(*args): return _lisa.VecDouble_end(*args)
    def rbegin(*args): return _lisa.VecDouble_rbegin(*args)
    def rend(*args): return _lisa.VecDouble_rend(*args)
    def pop_back(*args): return _lisa.VecDouble_pop_back(*args)
    def erase(*args): return _lisa.VecDouble_erase(*args)
    def __init__(self, *args): 
        this = _lisa.new_VecDouble(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(*args): return _lisa.VecDouble_push_back(*args)
    def front(*args): return _lisa.VecDouble_front(*args)
    def back(*args): return _lisa.VecDouble_back(*args)
    def assign(*args): return _lisa.VecDouble_assign(*args)
    def resize(*args): return _lisa.VecDouble_resize(*args)
    def insert(*args): return _lisa.VecDouble_insert(*args)
    def reserve(*args): return _lisa.VecDouble_reserve(*args)
    def capacity(*args): return _lisa.VecDouble_capacity(*args)
    __swig_destroy__ = _lisa.delete_VecDouble
    __del__ = lambda self : None;
VecDouble_swigregister = _lisa.VecDouble_swigregister
VecDouble_swigregister(VecDouble)

class VecVecDouble(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VecVecDouble, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VecVecDouble, name)
    __repr__ = _swig_repr
    def iterator(*args): return _lisa.VecVecDouble_iterator(*args)
    def __iter__(self): return self.iterator()
    def __nonzero__(*args): return _lisa.VecVecDouble___nonzero__(*args)
    def __len__(*args): return _lisa.VecVecDouble___len__(*args)
    def pop(*args): return _lisa.VecVecDouble_pop(*args)
    def __getslice__(*args): return _lisa.VecVecDouble___getslice__(*args)
    def __setslice__(*args): return _lisa.VecVecDouble___setslice__(*args)
    def __delslice__(*args): return _lisa.VecVecDouble___delslice__(*args)
    def __delitem__(*args): return _lisa.VecVecDouble___delitem__(*args)
    def __getitem__(*args): return _lisa.VecVecDouble___getitem__(*args)
    def __setitem__(*args): return _lisa.VecVecDouble___setitem__(*args)
    def append(*args): return _lisa.VecVecDouble_append(*args)
    def empty(*args): return _lisa.VecVecDouble_empty(*args)
    def size(*args): return _lisa.VecVecDouble_size(*args)
    def clear(*args): return _lisa.VecVecDouble_clear(*args)
    def swap(*args): return _lisa.VecVecDouble_swap(*args)
    def get_allocator(*args): return _lisa.VecVecDouble_get_allocator(*args)
    def begin(*args): return _lisa.VecVecDouble_begin(*args)
    def end(*args): return _lisa.VecVecDouble_end(*args)
    def rbegin(*args): return _lisa.VecVecDouble_rbegin(*args)
    def rend(*args): return _lisa.VecVecDouble_rend(*args)
    def pop_back(*args): return _lisa.VecVecDouble_pop_back(*args)
    def erase(*args): return _lisa.VecVecDouble_erase(*args)
    def __init__(self, *args): 
        this = _lisa.new_VecVecDouble(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(*args): return _lisa.VecVecDouble_push_back(*args)
    def front(*args): return _lisa.VecVecDouble_front(*args)
    def back(*args): return _lisa.VecVecDouble_back(*args)
    def assign(*args): return _lisa.VecVecDouble_assign(*args)
    def resize(*args): return _lisa.VecVecDouble_resize(*args)
    def insert(*args): return _lisa.VecVecDouble_insert(*args)
    def reserve(*args): return _lisa.VecVecDouble_reserve(*args)
    def capacity(*args): return _lisa.VecVecDouble_capacity(*args)
    __swig_destroy__ = _lisa.delete_VecVecDouble
    __del__ = lambda self : None;
VecVecDouble_swigregister = _lisa.VecVecDouble_swigregister
VecVecDouble_swigregister(VecVecDouble)

class VecInt(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VecInt, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VecInt, name)
    __repr__ = _swig_repr
    def iterator(*args): return _lisa.VecInt_iterator(*args)
    def __iter__(self): return self.iterator()
    def __nonzero__(*args): return _lisa.VecInt___nonzero__(*args)
    def __len__(*args): return _lisa.VecInt___len__(*args)
    def pop(*args): return _lisa.VecInt_pop(*args)
    def __getslice__(*args): return _lisa.VecInt___getslice__(*args)
    def __setslice__(*args): return _lisa.VecInt___setslice__(*args)
    def __delslice__(*args): return _lisa.VecInt___delslice__(*args)
    def __delitem__(*args): return _lisa.VecInt___delitem__(*args)
    def __getitem__(*args): return _lisa.VecInt___getitem__(*args)
    def __setitem__(*args): return _lisa.VecInt___setitem__(*args)
    def append(*args): return _lisa.VecInt_append(*args)
    def empty(*args): return _lisa.VecInt_empty(*args)
    def size(*args): return _lisa.VecInt_size(*args)
    def clear(*args): return _lisa.VecInt_clear(*args)
    def swap(*args): return _lisa.VecInt_swap(*args)
    def get_allocator(*args): return _lisa.VecInt_get_allocator(*args)
    def begin(*args): return _lisa.VecInt_begin(*args)
    def end(*args): return _lisa.VecInt_end(*args)
    def rbegin(*args): return _lisa.VecInt_rbegin(*args)
    def rend(*args): return _lisa.VecInt_rend(*args)
    def pop_back(*args): return _lisa.VecInt_pop_back(*args)
    def erase(*args): return _lisa.VecInt_erase(*args)
    def __init__(self, *args): 
        this = _lisa.new_VecInt(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(*args): return _lisa.VecInt_push_back(*args)
    def front(*args): return _lisa.VecInt_front(*args)
    def back(*args): return _lisa.VecInt_back(*args)
    def assign(*args): return _lisa.VecInt_assign(*args)
    def resize(*args): return _lisa.VecInt_resize(*args)
    def insert(*args): return _lisa.VecInt_insert(*args)
    def reserve(*args): return _lisa.VecInt_reserve(*args)
    def capacity(*args): return _lisa.VecInt_capacity(*args)
    __swig_destroy__ = _lisa.delete_VecInt
    __del__ = lambda self : None;
VecInt_swigregister = _lisa.VecInt_swigregister
VecInt_swigregister(VecInt)

class VecVecInt(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VecVecInt, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VecVecInt, name)
    __repr__ = _swig_repr
    def iterator(*args): return _lisa.VecVecInt_iterator(*args)
    def __iter__(self): return self.iterator()
    def __nonzero__(*args): return _lisa.VecVecInt___nonzero__(*args)
    def __len__(*args): return _lisa.VecVecInt___len__(*args)
    def pop(*args): return _lisa.VecVecInt_pop(*args)
    def __getslice__(*args): return _lisa.VecVecInt___getslice__(*args)
    def __setslice__(*args): return _lisa.VecVecInt___setslice__(*args)
    def __delslice__(*args): return _lisa.VecVecInt___delslice__(*args)
    def __delitem__(*args): return _lisa.VecVecInt___delitem__(*args)
    def __getitem__(*args): return _lisa.VecVecInt___getitem__(*args)
    def __setitem__(*args): return _lisa.VecVecInt___setitem__(*args)
    def append(*args): return _lisa.VecVecInt_append(*args)
    def empty(*args): return _lisa.VecVecInt_empty(*args)
    def size(*args): return _lisa.VecVecInt_size(*args)
    def clear(*args): return _lisa.VecVecInt_clear(*args)
    def swap(*args): return _lisa.VecVecInt_swap(*args)
    def get_allocator(*args): return _lisa.VecVecInt_get_allocator(*args)
    def begin(*args): return _lisa.VecVecInt_begin(*args)
    def end(*args): return _lisa.VecVecInt_end(*args)
    def rbegin(*args): return _lisa.VecVecInt_rbegin(*args)
    def rend(*args): return _lisa.VecVecInt_rend(*args)
    def pop_back(*args): return _lisa.VecVecInt_pop_back(*args)
    def erase(*args): return _lisa.VecVecInt_erase(*args)
    def __init__(self, *args): 
        this = _lisa.new_VecVecInt(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(*args): return _lisa.VecVecInt_push_back(*args)
    def front(*args): return _lisa.VecVecInt_front(*args)
    def back(*args): return _lisa.VecVecInt_back(*args)
    def assign(*args): return _lisa.VecVecInt_assign(*args)
    def resize(*args): return _lisa.VecVecInt_resize(*args)
    def insert(*args): return _lisa.VecVecInt_insert(*args)
    def reserve(*args): return _lisa.VecVecInt_reserve(*args)
    def capacity(*args): return _lisa.VecVecInt_capacity(*args)
    __swig_destroy__ = _lisa.delete_VecVecInt
    __del__ = lambda self : None;
VecVecInt_swigregister = _lisa.VecVecInt_swigregister
VecVecInt_swigregister(VecVecInt)

class VecUINT8(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VecUINT8, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VecUINT8, name)
    __repr__ = _swig_repr
    def iterator(*args): return _lisa.VecUINT8_iterator(*args)
    def __iter__(self): return self.iterator()
    def __nonzero__(*args): return _lisa.VecUINT8___nonzero__(*args)
    def __len__(*args): return _lisa.VecUINT8___len__(*args)
    def pop(*args): return _lisa.VecUINT8_pop(*args)
    def __getslice__(*args): return _lisa.VecUINT8___getslice__(*args)
    def __setslice__(*args): return _lisa.VecUINT8___setslice__(*args)
    def __delslice__(*args): return _lisa.VecUINT8___delslice__(*args)
    def __delitem__(*args): return _lisa.VecUINT8___delitem__(*args)
    def __getitem__(*args): return _lisa.VecUINT8___getitem__(*args)
    def __setitem__(*args): return _lisa.VecUINT8___setitem__(*args)
    def append(*args): return _lisa.VecUINT8_append(*args)
    def empty(*args): return _lisa.VecUINT8_empty(*args)
    def size(*args): return _lisa.VecUINT8_size(*args)
    def clear(*args): return _lisa.VecUINT8_clear(*args)
    def swap(*args): return _lisa.VecUINT8_swap(*args)
    def get_allocator(*args): return _lisa.VecUINT8_get_allocator(*args)
    def begin(*args): return _lisa.VecUINT8_begin(*args)
    def end(*args): return _lisa.VecUINT8_end(*args)
    def rbegin(*args): return _lisa.VecUINT8_rbegin(*args)
    def rend(*args): return _lisa.VecUINT8_rend(*args)
    def pop_back(*args): return _lisa.VecUINT8_pop_back(*args)
    def erase(*args): return _lisa.VecUINT8_erase(*args)
    def __init__(self, *args): 
        this = _lisa.new_VecUINT8(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(*args): return _lisa.VecUINT8_push_back(*args)
    def front(*args): return _lisa.VecUINT8_front(*args)
    def back(*args): return _lisa.VecUINT8_back(*args)
    def assign(*args): return _lisa.VecUINT8_assign(*args)
    def resize(*args): return _lisa.VecUINT8_resize(*args)
    def insert(*args): return _lisa.VecUINT8_insert(*args)
    def reserve(*args): return _lisa.VecUINT8_reserve(*args)
    def capacity(*args): return _lisa.VecUINT8_capacity(*args)
    __swig_destroy__ = _lisa.delete_VecUINT8
    __del__ = lambda self : None;
VecUINT8_swigregister = _lisa.VecUINT8_swigregister
VecUINT8_swigregister(VecUINT8)

class VecVecUINT8(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VecVecUINT8, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VecVecUINT8, name)
    __repr__ = _swig_repr
    def iterator(*args): return _lisa.VecVecUINT8_iterator(*args)
    def __iter__(self): return self.iterator()
    def __nonzero__(*args): return _lisa.VecVecUINT8___nonzero__(*args)
    def __len__(*args): return _lisa.VecVecUINT8___len__(*args)
    def pop(*args): return _lisa.VecVecUINT8_pop(*args)
    def __getslice__(*args): return _lisa.VecVecUINT8___getslice__(*args)
    def __setslice__(*args): return _lisa.VecVecUINT8___setslice__(*args)
    def __delslice__(*args): return _lisa.VecVecUINT8___delslice__(*args)
    def __delitem__(*args): return _lisa.VecVecUINT8___delitem__(*args)
    def __getitem__(*args): return _lisa.VecVecUINT8___getitem__(*args)
    def __setitem__(*args): return _lisa.VecVecUINT8___setitem__(*args)
    def append(*args): return _lisa.VecVecUINT8_append(*args)
    def empty(*args): return _lisa.VecVecUINT8_empty(*args)
    def size(*args): return _lisa.VecVecUINT8_size(*args)
    def clear(*args): return _lisa.VecVecUINT8_clear(*args)
    def swap(*args): return _lisa.VecVecUINT8_swap(*args)
    def get_allocator(*args): return _lisa.VecVecUINT8_get_allocator(*args)
    def begin(*args): return _lisa.VecVecUINT8_begin(*args)
    def end(*args): return _lisa.VecVecUINT8_end(*args)
    def rbegin(*args): return _lisa.VecVecUINT8_rbegin(*args)
    def rend(*args): return _lisa.VecVecUINT8_rend(*args)
    def pop_back(*args): return _lisa.VecVecUINT8_pop_back(*args)
    def erase(*args): return _lisa.VecVecUINT8_erase(*args)
    def __init__(self, *args): 
        this = _lisa.new_VecVecUINT8(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(*args): return _lisa.VecVecUINT8_push_back(*args)
    def front(*args): return _lisa.VecVecUINT8_front(*args)
    def back(*args): return _lisa.VecVecUINT8_back(*args)
    def assign(*args): return _lisa.VecVecUINT8_assign(*args)
    def resize(*args): return _lisa.VecVecUINT8_resize(*args)
    def insert(*args): return _lisa.VecVecUINT8_insert(*args)
    def reserve(*args): return _lisa.VecVecUINT8_reserve(*args)
    def capacity(*args): return _lisa.VecVecUINT8_capacity(*args)
    __swig_destroy__ = _lisa.delete_VecVecUINT8
    __del__ = lambda self : None;
VecVecUINT8_swigregister = _lisa.VecVecUINT8_swigregister
VecVecUINT8_swigregister(VecVecUINT8)

DevFromMean = _lisa.DevFromMean
StandardizeData = _lisa.StandardizeData
class OgSet(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, OgSet, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, OgSet, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _lisa.new_OgSet(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _lisa.delete_OgSet
    __del__ = lambda self : None;
    def Belongs(*args): return _lisa.OgSet_Belongs(*args)
    def Push(*args): return _lisa.OgSet_Push(*args)
    def Pop(*args): return _lisa.OgSet_Pop(*args)
    def Size(*args): return _lisa.OgSet_Size(*args)
OgSet_swigregister = _lisa.OgSet_swigregister
OgSet_swigregister(OgSet)

class GeodaLisa(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, GeodaLisa, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, GeodaLisa, name)
    __repr__ = _swig_repr
    __swig_getmethods__["LISA"] = lambda x: _lisa.GeodaLisa_LISA
    if _newclass:LISA = staticmethod(_lisa.GeodaLisa_LISA)
    __swig_getmethods__["MLISA"] = lambda x: _lisa.GeodaLisa_MLISA
    if _newclass:MLISA = staticmethod(_lisa.GeodaLisa_MLISA)
    def __init__(self, *args): 
        this = _lisa.new_GeodaLisa(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _lisa.delete_GeodaLisa
    __del__ = lambda self : None;
GeodaLisa_swigregister = _lisa.GeodaLisa_swigregister
GeodaLisa_swigregister(GeodaLisa)
GeodaLisa_LISA = _lisa.GeodaLisa_LISA
GeodaLisa_MLISA = _lisa.GeodaLisa_MLISA



