#----------------------------------------------------------------------
# This file was generated by C:\Python27\Scripts\img2py-script.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

logo = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAABXhJ"
    "REFUWIXtlV1wVdUVx39rn3Nubm5uQmIaBzWChFgngOgUxtDWMdAUED9aLJzQWlHsDE4f+FAL"
    "b5Kb0HZGoAMSZvwaO3RQ1N7rTCtqaWAUoh1xJAoFEtsH6ENDA3QoSUhyk3PP2asPJyIV2ulj"
    "Z5r/zJm9z/76r73Wf60N4xjHOMYxjv81KEgW3zlAg3uABlfxHUAun9cMrmYw/7Ixi4OPgyJk"
    "cMlkDOh/+hzIOl86w3f0MrLLSQFUkSuIQbhy7L+ENe7l5E3kotPcl/qMsHEUOz3ApkqQQ1lW"
    "7oOmSAQOK871ZaxJevSeWsOvsz6mqZWILTyCSiMFynHVMKGmhR8vO423rpLCNRaIYk8GDkxU"
    "SE+E8jVufEPfEXJRFwu/28voUy7ygYscC6FuCH2nhhfbgUUbFPnW0/x2oJx7JgSsB2jKEfG0"
    "vEpEBcXeTygNhsl7q9i+6zA0jhBuErARaBLEggZw0UK+AOYA2TjGHGfh2k6+3d/DPbcDHKDB"
    "BehmwfxO03gQoOIXPOf+jM/0p2jVNlYCpLeylM3SRzslX7h2RxoaFkLVrbBoIky6HVQh/QJc"
    "WwJTq+GZIgC3iVzUxfxFFp4px2us5ndHT+An/s45m8V36vyuDsl176/cyhMjBWquLWEFykef"
    "UxWs3EYBwwJCADK4TF+dp4n2WGgSwZTaeHX6IJwZgrOjICGoY5rJuMPocwXsnlr2vvcCs7wZ"
    "5IJ5dIS+n0Ny3cGk7czJhzx+5/X4xmMQoG+EFIDnaScllLJFnv1cWXRlNCafNqbyC/VxO+F4"
    "3DYAKiCRWU7nA0mcyQnMLwEqqLHq42gGV3JEzXtInQt4udhlfftyBtIOASF4UAkwuJY3CciS"
    "4kdskd20YGhttXG8u6MxP90BXh5Wnow11xGBKIDpZ/TeIUIqSR4D8JmmkiMCLEDbn3jeUw6d"
    "f5IswIxKep08kbVMBlAfB18fYYg3SfIgm2V3TKrERgCEs8Ech3V5H9+ROKsFwIwQ3RJig9l8"
    "ZSAebbU3t7E4neAd2ci+PuWh4YAbnFZ2V20mt/8UL0cOjoWbAJoApjDKev0eeV4nRRPbeHLs"
    "hgpLq2CkBpyPAbINWW/DXc3OErvUAGIUNRYSf+RMMcASxUknyU8uY1OiiPoJKbaUJt0NoxFv"
    "943wWnUJPy8S/iCWme/9hWQuR+RnMRgsr+vDXKSbYVmFRmMF7XBd3El9CHC3+8rKaNeUZV5i"
    "0cP5IBRThneiAo9zhPUA275enTjyGO2nB7k1UcTFwVfvfuP9dd/5mruR144cn/Z212o6JyZ4"
    "90Ka8sf3shigqwuH7RTxKQUSug0hTYuJBWguzFKAxJwj/efnf9PeJUUbz9be+FjhZOkS78E7"
    "TRHOzlEsg4Rbz3J/7aSPevJWG9wgwdq/Hb1GPjgk2WS67wxAWfWAA7A0ycE2hGP9siyuFYRc"
    "N5aGVuaQ4Pe0yth/MBu8PMGeU6dq7NR5Ld0De3vKq96iLC9Bz40CcIIFjw4RPe8K7rCaTyur"
    "+6O6dR/X93dc9+eTv7n3h7N46ZMMmJY4dzTfjNlbzIcPpaR+eIRfuSl9MVQMeXkU5avcUHEf"
    "y/8xEIfAOWnECawGdbc0n0jv+OvqVdH5mX1tU6eXrKiv32GUjJnBvp1TKLsJlRURhbfCvqKd"
    "tRFzn9rUe8csXvpEwbSCFVBVpHgjtlDK4nmh/oCQqqhfNjEsT+DqUWbq/C/Imw0Ut1mdtBrA"
    "l+zwN3qLXkmY/fu1p2zXsu/fFgBcKsdfhqKiZK546TSW+BWvJgAZDPpv5q6CSwszZMxcDl4i"
    "m5vtUHysCHq1jVaReS04HdNRulC6EaYhtBLFNl4y1x2zOQKwIIIdIzZXPXsc/1/4J1mKNafj"
    "LICwAAAAAElFTkSuQmCC")
getlogoData = logo.GetData
getlogoImage = logo.GetImage
getlogoBitmap = logo.GetBitmap

