img2py ToolBarBitmaps_2.png toolbarimages.py
img2py -a ToolBarBitmaps_2_disabled.png toolbarimages.py
img2py -a ToolBarBitmaps_3.png toolbarimages.py
img2py -a ToolBarBitmaps_3_disabled.png toolbarimages.py
img2py -a ToolBarBitmaps_4.png toolbarimages.py
img2py -a ToolBarBitmaps_4_disabled.png toolbarimages.py
img2py -a ToolBarBitmaps_5.png toolbarimages.py
img2py -a ToolBarBitmaps_5_disabled.png toolbarimages.py
img2py -a ToolBarBitmaps_6.png toolbarimages.py
img2py -a ToolBarBitmaps_6_disabled.png toolbarimages.py
img2py -a ToolBarBitmaps_7.png toolbarimages.py
img2py -a ToolBarBitmaps_7_disabled.png toolbarimages.py
img2py -a ToolBarBitmaps_8.png toolbarimages.py
img2py -a ToolBarBitmaps_8_disabled.png toolbarimages.py
img2py -a ToolBarBitmaps_9.png toolbarimages.py
img2py -a ToolBarBitmaps_9_disabled.png toolbarimages.py
img2py -a ToolBarBitmaps_10.png toolbarimages.py
img2py -a ToolBarBitmaps_10_disabled.png toolbarimages.py
img2py -a ToolBarBitmaps_11.png toolbarimages.py
img2py -a ToolBarBitmaps_11_disabled.png toolbarimages.py
img2py -a ToolBarBitmaps_12.png toolbarimages.py
img2py -a ToolBarBitmaps_12_disabled.png toolbarimages.py
img2py -a ToolBarBitmaps_13.png toolbarimages.py
img2py -a ToolBarBitmaps_13_disabled.png toolbarimages.py
img2py -a ToolBarBitmaps_14.png toolbarimages.py
img2py -a ToolBarBitmaps_14_disabled.png toolbarimages.py
img2py -a ToolBarBitmaps_15.png toolbarimages.py
img2py -a ToolBarBitmaps_15_disabled.png toolbarimages.py
img2py -a ToolBarBitmaps_16.png toolbarimages.py
img2py -a ToolBarBitmaps_16_disabled.png toolbarimages.py
img2py -a ToolBarBitmaps_17.png toolbarimages.py
img2py -a ToolBarBitmaps_17_disabled.png toolbarimages.py
img2py -a ToolBarBitmaps_18.png toolbarimages.py
img2py -a ToolBarBitmaps_18_disabled.png toolbarimages.py
img2py -a ToolBarBitmaps_19.png toolbarimages.py
img2py -a ToolBarBitmaps_19_disabled.png toolbarimages.py
img2py -a ToolBarBitmaps_20.png toolbarimages.py
img2py -a ToolBarBitmaps_20_disabled.png toolbarimages.py
img2py -a ToolBarBitmaps_21.png toolbarimages.py
img2py -a ToolBarBitmaps_21_disabled.png toolbarimages.py
img2py -a ToolBarBitmaps_22.png toolbarimages.py
img2py -a ToolBarBitmaps_22_disabled.png toolbarimages.py
img2py -a ToolBarBitmaps_23.png toolbarimages.py
img2py -a ToolBarBitmaps_23_disabled.png toolbarimages.py
img2py -a ToolBarBitmaps_24.png toolbarimages.py
img2py -a ToolBarBitmaps_24_disabled.png toolbarimages.py
img2py -a ToolBarBitmaps_25.png toolbarimages.py
img2py -a ToolBarBitmaps_25_disabled.png toolbarimages.py
img2py -a ToolBarBitmaps_26.png toolbarimages.py
img2py -a ToolBarBitmaps_26_disabled.png toolbarimages.py
img2py -a ToolBarBitmaps_27.png toolbarimages.py
img2py -a ToolBarBitmaps_27_disabled.png toolbarimages.py
img2py -a ToolBarBitmaps_28.png toolbarimages.py
img2py -a ToolBarBitmaps_28_disabled.png toolbarimages.py
img2py -a ToolBarBitmaps_29.png toolbarimages.py
img2py -a ToolBarBitmaps_29_disabled.png toolbarimages.py
img2py -a ToolBarBitmaps_30.png toolbarimages.py
img2py -a ToolBarBitmaps_30_disabled.png toolbarimages.py
img2py -a ToolBarBitmaps_31_disabled.png toolbarimages.py
img2py -a ToolBarBitmaps_32.png toolbarimages.py
img2py -a ToolBarBitmaps_32_disabled.png toolbarimages.py
img2py -a ToolBarBitmaps_33.png toolbarimages.py
img2py -a ToolBarBitmaps_33_disabled.png toolbarimages.py
img2py -a ToolBarBitmaps_34.png toolbarimages.py
img2py -a ToolBarBitmaps_34_disabled.png toolbarimages.py
img2py -a ToolBarBitmaps_35.png toolbarimages.py
img2py -a ToolBarBitmaps_35_disabled.png toolbarimages.py
img2py -a ToolBarBitmaps_36.png toolbarimages.py
img2py -a ToolBarBitmaps_36_disabled.png toolbarimages.py
img2py -a ToolBarBitmaps_37.png toolbarimages.py
img2py -a ToolBarBitmaps_37_disabled.png toolbarimages.py
img2py -a ToolBarBitmaps_38.png toolbarimages.py
img2py -a ToolBarBitmaps_38_disabled.png toolbarimages.py
img2py -a ToolBarBitmaps_39.png toolbarimages.py
img2py -a ToolBarBitmaps_39_disabled.png toolbarimages.py
img2py -a ToolBarBitmaps_40.png toolbarimages.py
img2py -a ToolBarBitmaps_40_disabled.png toolbarimages.py
#
img2py -a ToolBar-open-folder.png toolbarimages.py
img2py -a ToolBar-open-folder_disabled.png toolbarimages.py
img2py -a ToolBar-close-folder.png toolbarimages.py
img2py -a ToolBar-close-folder_disabled.png toolbarimages.py
img2py -a ToolBarBitmaps_MapChoices.png toolbarimages.py
img2py -a ToolBarBitmaps_MapChoices_disabled.png toolbarimages.py
img2py -a ToolBar_down_arrow.png toolbarimages.py
img2py -a ToolBar_down_arrow_disabled.png toolbarimages.py
#
img2py -a ToolBar-Dynamic_LISA.png toolbarimages.py
img2py -a ToolBar-trend_graph.png toolbarimages.py
img2py -a ToolBar-weights_map.png toolbarimages.py
img2py -a ToolBar_brush.png toolbarimages.py
img2py -a ToolBar_calendar.png toolbarimages.py
img2py -a ToolBar_export.png toolbarimages.py
img2py -a ToolBar_extent.png toolbarimages.py
img2py -a ToolBar_hand.png toolbarimages.py
img2py -a ToolBar_pause.png toolbarimages.py
img2py -a ToolBar_play.png toolbarimages.py
img2py -a ToolBar_refresh.png toolbarimages.py
img2py -a ToolBar_select.gif toolbarimages.py
img2py -a ToolBar_stop.png toolbarimages.py
img2py -a ToolBar_zoom.png toolbarimages.py
#
img2py -a open-folder.png toolbarimages.py
img2py -a about-geoda-logo.png toolbarimages.py
#########
# images for gradient density map
img2py stars-gradient-classic.png gradientimages.py
img2py -a stars-gradient-fire.png gradientimages.py
img2py -a stars-gradient-omg.png gradientimages.py
img2py -a stars-gradient-pbj.png gradientimages.py
img2py -a stars-gradient-pgaitch.png gradientimages.py
img2py -a stars-gradient-RdYIBu.png gradientimages.py
########
# image for logo
img2py -i stars-logo.ico logoimages.py
